name: SaFF-Net/conda
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=pyhd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.2=pyhd33586a_0
  - ipython=8.21.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py310h06a4308_0
  - joblib=1.2.0=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_core=5.7.1=py310hff52083_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.42.0=py310h6a678d5_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - numba=0.59.0=py310h6a678d5_0
  - numpy=1.26.3=py310h5f9d8c6_0
  - numpy-base=1.26.3=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py310h5eee18b_0
  - pip=23.3.1=py310h06a4308_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pynndescent=0.5.11=pyhca7485f_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.2.0=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - pyzmq=25.1.2=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_1
  - setuptools=68.2.2=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.2.0=py310_cu121
  - torchtriton=2.2.0=py310
  - torchvision=0.17.0=py310_cu121
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing_extensions=4.9.0=py310h06a4308_1
  - umap-learn=0.5.5=py310hff52083_1
  - urllib3=2.1.0=py310h06a4308_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.16.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - defusedxml==0.7.1
      - fastjsonschema==2.19.1
      - fire==0.5.0
      - fonttools==4.48.1
      - fqdn==1.5.1
      - fsspec==2024.2.0
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - imageio==2.33.1
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - json5==0.9.17
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.2
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - matplotlib==3.8.2
      - medmnist==3.0.1
      - mistune==3.0.2
      - nbclient==0.9.0
      - nbconvert==7.16.1
      - nbformat==5.9.2
      - notebook==7.1.0
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandas==2.2.0
      - pandocfilters==1.5.1
      - prometheus-client==0.20.0
      - pyarrow==15.0.0
      - pycparser==2.21
      - pydicom==2.4.4
      - pyparsing==3.1.1
      - python-json-logger==2.0.7
      - pytorch-metric-learning==2.4.1
      - pytorch-msssim==1.0.0
      - pytz==2024.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.33.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - scikit-image==0.22.0
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.5
      - termcolor==2.4.0
      - terminado==0.18.0
      - tifffile==2024.1.30
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.4
      - tqdm==4.66.1
      - types-python-dateutil==2.8.19.20240106
      - tzdata==2023.4
      - uri-template==1.3.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - widgetsnbextension==4.0.10
